name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Write Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
            {
                "id": "github",
                "name": "github",
                "url": "https://maven.pkg.github.com/edoardopelli/releases",
                "releases": {
                  "enabled": "true"
                }
              }
              ]
            servers: >
              [
                {
                  "id": "github",
                  "username": "${env.GIT_USERNAME}",
                  "password": "${env.GITHUB_TOKEN}",
                  "configuration": {
                  "httpConfiguration": {
                      "all": {
                        "usePreemptive": "true"
                      }
                    }
                  }
                }
              ]
  
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_SECRET }}
          GIT_USERNAME: edoardopelli
        run:  |
              mkdir -p ~/.ssh
              echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              git config --global user.name "edoardopelli"
              git config --global user.email "edoardo.pelli@gmail.com"
              git config --global user.password "${GITHUB_TOKEN}"
              mvn --batch-mode -e release:prepare release:perform


    