name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: edoardopelli
        run:  |
              echo '<?xml version="1.0" encoding="UTF-8"?>' > $HOME/.m2/settings.xml
              echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"' >> $HOME/.m2/settings.xml
              echo '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' >> $HOME/.m2/settings.xml
              echo '         xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0' >> $HOME/.m2/settings.xml
              echo '                             http://maven.apache.org/xsd/settings-1.0.0.xsd">' >> $HOME/.m2/settings.xml
              echo '  <servers>' >> $HOME/.m2/settings.xml
              echo '    <server>' >> $HOME/.m2/settings.xml
              echo '      <id>github</id>' >> $HOME/.m2/settings.xml
              echo '      <username>edoardopelli</username>' >> $HOME/.m2/settings.xml
              echo '      <password>${GITHUB_TOKEN}</password>' >> $HOME/.m2/settings.xml
              echo '    </server>' >> $HOME/.m2/settings.xml
              echo '  </servers>' >> $HOME/.m2/settings.xml
              echo '</settings>' >> $HOME/.m2/settings.xml
              git config --global user.name "edoardopelli"
              git config --global user.email "edoardo.pelli@gmail.com"
              git config --global user.password "${env.GITHUB_TOKEN}"
              mvn --batch-mode -e release:prepare release:perform


    