name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn release:prepare release:perform
        env:
          GITHUB_TOKEN: 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