name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: edoardopelli
        run:  |
              echo "<settings><servers><server><id>github</id><username>edoardopelli</username><password>${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
              git config --global user.name "edoardopelli"
              git config --global user.email "edoardo.pelli@gmail.com"
              git config --global user.password "${GITHUB_TOKEN}"
              mvn --batch-mode -e release:prepare release:perform


    